import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../models/event_model.dart';
import '../controllers/event_service.dart';

class AddEventPage extends StatefulWidget {
  @override
  _AddEventPageState createState() => _AddEventPageState();
}

class _AddEventPageState extends State<AddEventPage> {
  final _formKey = GlobalKey<FormState>();
  TextEditingController _titleController = TextEditingController();
  TextEditingController _dateController = TextEditingController();
  TextEditingController _startTimeController = TextEditingController();
  TextEditingController _endTimeController = TextEditingController();
  TextEditingController _descController = TextEditingController();
  final EventService _eventService = EventService();

  void _selectDate(BuildContext context, TextEditingController controller) async {
    DateTime? selectedDate = await showDatePicker(
      context: context,
      initialDate: DateTime.now(),
      firstDate: DateTime(2000),
      lastDate: DateTime(2101),
    );

    if (selectedDate != null) {
      setState(() {
        controller.text = DateFormat('dd/MM/yyyy').format(selectedDate);
      });
    }
  }

  void _selectTime(BuildContext context, TextEditingController controller) async {
    TimeOfDay? selectedTime = await showTimePicker(
      context: context,
      initialTime: TimeOfDay.now(),
    );

    if (selectedTime != null) {
      setState(() {
        controller.text = selectedTime.format(context);
      });
    }
  }

  void _addEvent() async {
    if (_formKey.currentState?.validate() ?? false) {
      final eventName = _titleController.text;
      final description = _descController.text;
      final date = _dateController.text;
      final startTime = _startTimeController.text;
      final endTime = _endTimeController.text;

      final event = EventModel(
        id: '',  // ID will be generated by the server
        eventName: eventName,
        description: description,
        eventDate: DateTime.parse(DateFormat('dd/MM/yyyy').parse(date).toIso8601String()),
        startTime: startTime,
        endTime: endTime,
      );

      try {
        await _eventService.createEvent(
          eventName,
          description,
          DateTime.parse(DateFormat('dd/MM/yyyy').parse(date).toIso8601String()),
          startTime,
          endTime,
        );
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('กิจกรรมถูกบันทึกแล้ว!')),
        );
        Navigator.pop(context, true);
      } catch (e) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error creating event: $e')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color(0xFFEAF6FF),
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        iconTheme: IconThemeData(color: Colors.black),
        leading: IconButton(
          icon: Icon(Icons.arrow_back, color: Colors.white),
          onPressed: () => Navigator.of(context).pop(),
        ),
        flexibleSpace: Stack(
          children: [
            Positioned(
              top: -50,
              left: -110,
              right: 270,
              child: Container(
                height: 100,
                decoration: BoxDecoration(
                  gradient: LinearGradient(
                    colors: [Color.fromARGB(223, 4, 15, 137), Colors.cyan],
                    begin: Alignment.bottomRight,
                    end: Alignment.bottomCenter,
                  ),
                  borderRadius: BorderRadius.vertical(
                    bottom: Radius.circular(200),
                  ),
                ),
                child: Align(
                  alignment: Alignment.bottomCenter,
                  child: Padding(
                    padding: const EdgeInsets.only(bottom: 20.0),
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            Text(
              'เพิ่มกิจกรรม',
              style: TextStyle(fontSize: 24.0, fontWeight: FontWeight.bold, color: Colors.black),
              textAlign: TextAlign.center,
            ),
            SizedBox(height: 24.0),
            Expanded(
              child: Form(
                key: _formKey,
                child: ListView(
                  children: [
                    _buildLabel('ชื่อกิจกรรม'),
                    _buildTextField(
                      controller: _titleController,
                      hintText: 'ชื่อกิจกรรม',
                      validator: (value) {
                        if (value == null || value.isEmpty) {
                          return 'กรุณาใส่ชื่อกิจกรรม';
                        }
                        return null;
                      },
                    ),
                    SizedBox(height: 16.0),
                    _buildLabel('คำอธิบายของกิจกรรม'),
                    _buildTextField(
                      controller: _descController,
                      hintText: 'คำอธิบาย',
                      validator: (value) {
                        if (value == null || value.isEmpty) {
                          return 'กรุณาใส่คำอธิบาย';
                        }
                        return null;
                      },
                    ),
                    SizedBox(height: 16.0),
                    _buildLabel('วันที่จัดงาน'),
                    _buildTextField(
                      controller: _dateController,
                      hintText: 'ว/ด/ป',
                      readOnly: true,
                      onTap: () => _selectDate(context, _dateController),
                      validator: (value) {
                        if (value == null || value.isEmpty) {
                          return 'กรุณาเลือกวันที่';
                        }
                        return null;
                      },
                      icon: Icons.calendar_today,
                    ),
                    SizedBox(height: 16.0),
                    _buildLabel('เวลาเริ่มกิจกรรม'),
                    _buildTextField(
                      controller: _startTimeController,
                      hintText: '00.00',
                      readOnly: true,
                      onTap: () => _selectTime(context, _startTimeController),
                      validator: (value) {
                        if (value == null || value.isEmpty) {
                          return 'กรุณาเลือกเวลาเริ่ม';
                        }
                        return null;
                      },
                      icon: Icons.access_time,
                    ),
                    SizedBox(height: 16.0),
                    _buildLabel('เวลาสิ้นสุดกิจกรรม'),
                    _buildTextField(
                      controller: _endTimeController,
                      hintText: '00.00',
                      readOnly: true,
                      onTap: () => _selectTime(context, _endTimeController),
                      validator: (value) {
                        if (value == null || value.isEmpty) {
                          return 'กรุณาเลือกเวลาสิ้นสุด';
                        }
                        return null;
                      },
                      icon: Icons.access_time,
                    ),
                    SizedBox(height: 24.0),
                    Container(
                      width: double.infinity,
                      decoration: BoxDecoration(
                        gradient: LinearGradient(
                          colors: [Color(0xFF00A9F0), Color.fromARGB(255, 8, 96, 190)],
                          begin: Alignment.centerLeft,
                          end: Alignment.bottomRight,
                        ),
                        borderRadius: BorderRadius.circular(8.0),
                      ),
                      child: ElevatedButton(
                        onPressed: _addEvent,
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Icon(Icons.save, color: Colors.white),
                            SizedBox(width: 8.0),
                            Text(
                              'บันทึกกิจกรรม',
                              style: TextStyle(color: Colors.white),
                            ),
                          ],
                        ),
                        style: ElevatedButton.styleFrom(
                          backgroundColor: Colors.transparent, // Set to transparent to show gradient
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(8.0),
                          ),
                          padding: EdgeInsets.symmetric(vertical: 16.0),
                          textStyle: TextStyle(fontSize: 18.0),
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildLabel(String text) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8.0),
      child: Text(
        text,
        style: TextStyle(fontSize: 16.0, fontWeight: FontWeight.bold),
      ),
    );
  }

  Widget _buildTextField({
    required TextEditingController controller,
    required String hintText,
    bool readOnly = false,
    Function()? onTap,
    String? Function(String?)? validator,
    IconData? icon,
  }) {
    return TextFormField(
      controller: controller,
      readOnly: readOnly,
      onTap: onTap,
      validator: validator,
      decoration: InputDecoration(
        hintText: hintText,
        suffixIcon: icon != null ? Icon(icon) : null,
        filled: true,
        fillColor: Colors.white,
        contentPadding: EdgeInsets.symmetric(vertical: 16.0, horizontal: 16.0),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8.0),
        ),
        enabledBorder: OutlineInputBorder(
          borderSide: BorderSide(color: Colors.grey.shade300),
          borderRadius: BorderRadius.circular(8.0),
        ),
        focusedBorder: OutlineInputBorder(
          borderSide: BorderSide(color: Color(0xFF00A9F0), width: 2.0),
          borderRadius: BorderRadius.circular(8.0),
        ),
      ),
    );
  }
}
